import ClientProvider from "@/contexts/ClientProvider";
import { cn } from "@/lib/utils";
import { getActions } from "@/store/auth-store";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import "./tree.css";

import { Toaster } from "@/components/ui/toaster";
import Notify from "@/components/ui/notify";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { init } = getActions();

  init();

  return (
    <html lang="en">
      <body
        className={cn(
          "grid h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ClientProvider>{children}</ClientProvider>
        <Toaster />
        <Notify />
      </body>
    </html>
  );
}
